services:
  db:
    image: mysql:8.1.0
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - TZ=${TZ}
    ports:
      - "3307:3306"
    volumes:
      - ./db/conf:/etc/mysql/conf.d/:ro
      - oicdb:/var/lib/mysql
      - ./db/logs:/var/log/mysql
      - ./sqls/:/sqls
    networks:
      - backend
  api:
    image: borygashill608/oicapi:latest
    restart: always
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_TYPE=${DB_TYPE}
      - BACKEND_URL=${BACKEND_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
      - GOOGLE_CALLBACK_LINK_URL=${GOOGLE_CALLBACK_LINK_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_SECRET=${GOOGLE_SECRET}
      - COOKIE_DOMAIN=${COOKIE_DOMAIN}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - JWT_SECRET=${JWT_SECRET}
      - LANG=${LANG}
      - LANGUAGE=${LANGUAGE}
      - LC_ALL=${LC_ALL}
      - NAVER_BAND_ACCESS_TOKEN=${NAVER_BAND_ACCESS_TOKEN}
      - BAND_KEY=${BAND_KEY}
      - X_API_KEY=${X_API_KEY}
      - X_API_KEY_SECRET=${X_API_KEY_SECRET}
      - X_ACCESS_TOKEN=${X_ACCESS_TOKEN}
      - X_ACCESS_TOKEN_SECRET=${X_ACCESS_TOKEN_SECRET}
      - X_BEARER_TOKEN=${X_BEARER_TOKEN}
    tty: true
    ports:
      - "3001:3000"
    volumes:
      - ./files:/files
    networks:
      - backend

  web:
    image: node:20-bullseye
    ports:
      - "3000:3000"
    volumes:
      - ./project_OIC-Frontend_NextJS-deployment-repo/web:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_BACKEND_URL=https://localhost.com/api
      - NEXT_PUBLIC_COOKIE_DOMAIN=localhost.com
      - NEXT_PUBLIC_TRANSLATION_URL=https://localhost.com/fastapi

networks:
  backend:

volumes:
  oicdb: